library("tidyverse")
library("ggplot2")
library("sjPlot")
library("ggeffects")
library("lme4")
library("Amelia")
library("table1")
library("formattable")
library("patchwork")
library("parameters")
library("prettycode")
library("styler")
library("gghighlight")
library("see")
library("viridis")
library("ggpubr")
#library("Manu")
library("wesanderson")
library("ggsci")
library("equatiomatic")
library("report")
library("ggpmisc")
library("brms")
library("readr")
library("lubridate")
library("rstan")
library("bmlm")
library("ggthemes")
library("correlation")
library("here")
library("ggraph")

# Settings for BRMS
rstan_options(auto_write=TRUE)
options(mc.cores=parallel::detectCores ())
